services:
  rabbitmq-stream:
    image: rabbitmq:3.13-rc-management
    container_name: rabbitmq-stream
    restart: unless-stopped
    hostname: "rabbitmq"
    ports:
      - "15672:15672"
      - "5671:5671"
      - "5672:5672"
      - "5551:5551"
      - "5552:5552"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbit"
      RABBITMQ_DEFAULT_PASS: "rabbit"
    volumes:
     - ./conf/:/etc/rabbitmq/
     - "./tls-gen/basic/result/:/certs"
